name: CI Metrics (Education)

on:
  push:
  workflow_dispatch:

# Não cancela runs antigos: coloca em FILA
concurrency:
  group: ci-metrics-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        squad: [A, B, C, D, E, F, G, H, I]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug paths (1x pra garantir)
        run: |
          ls -la
          ls -la scripts
          ls -la squads
          ls -la squads/squad-${{ matrix.squad }}

      - name: Install tools
        run: |
          npm install -g html-validate stylelint stylelint-config-standard cheerio css

      - name: Run HTML & CSS metrics
        run: |
          node scripts/collect_metrics.js squads/squad-${{ matrix.squad }} metrics-squad-${{ matrix.squad }}.json


      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics-squad-${{ matrix.squad }}
          path: metrics-squad-${{ matrix.squad }}.json

